config/routes.rb
Libertyhive::Application.routes.draw do

  match '/users/sign_up', :to => 'links#index'  #temporarily blocking open sign up

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
    
  resources :users do
    member do
      get :comments, :links, :upvoted
    end
  end
    
  resources :links
  resources :comments
  resources :votes
  
  root :to => 'links#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :profile_attributes
  
  has_one :profile
  accepts_nested_attributes_for :profile
  validates_associated :profile
  
  has_many :links, :foreign_key => "submitter_id"
  has_many :votes, :foreign_key => "voter_id"
  has_many :comments, :foreign_key => "commenter_id"
        
  def name
    profile.first_name + " " + profile.last_name
  end
  
  def karma
    vote_total(links) + vote_total(comments) + 1
  end
  
  def vote_for!(votable) 
    unless ineligible_to_vote_for? votable
      votes.create!(:votable_id => votable.id,
                    :votable_type => votable.class.name)
      votable.update_score  if votable.class.name == "Link"
    end
  end
  
  def ineligible_to_vote_for?(votable)
    already_voted_for?(votable) || is_submitter_of?(votable)
  end
  
  def is_submitter_of?(votable)
    votable.submitter.id == id
  end
  
  def already_voted_for?(votable)
    votable.votes.find_by_voter_id(id)
  end
  
  private
    
    def vote_total(votables)
      total = 0
      votables.each {|v| total += v.votes.count}
      return total
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
    @link_votes = @user.votes.select {|v| v.votable.class.name == "Link"}
    @activity = !@user.links.empty? || !@user.comments.empty? || !@link_votes.empty?
    @work = @user.profile.occupation.present? || @user.profile.organization.present?
    @any_url = @user.profile.linkedin_url.present? ||
                @user.profile.facebook_url.present? ||
                @user.profile.twitter_url.present? ||
                @user.profile.blog_url.present? ||
                @user.profile.personal_url.present?
  end

  def new
    redirect_to(links_path) if user_signed_in?
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html{ render :action => :edit } 
      else
        format.html{ render :action => :new }
      end
    end
  end
  
  def edit
    @user = User.find(params[:id])    
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def links
    @user = User.find(params[:id])
    @title = "Links Submitted by #{@user.name}"
    @links = @user.links.paginate(:page => params[:page])
  end
  
  def comments
    @user = User.find(params[:id])
    @title = "Comments by #{@user.name}"
    @comments = @user.comments.paginate(:page => params[:page])
  end
  
  def upvoted
    @user = User.find(params[:id])
    @title = "Links Upvoted by #{@user.name}"
    @all_upvoted_links = @user.votes.collect {|v| v.votable if v.votable_type == "Link"}
    @upvoted_links = @all_upvoted_links.paginate(:page => params[:page])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comment.html.erb
<li class="list-item">
	<%= render 	:partial => 'shared/vote',
							:locals => {:votable => comment}  %>
	<div class="item-main">
		<div class="meta-head">
		<%= render 	:partial => 'shared/meta', 
								:locals => {:item => comment,
														:ref_link => link_to("link", comment),
														:ref_link2 => link_to("full discussion", comment.link)} %>
		</div>
		<div>
			<%= comment.content.html_safe %>
		</div>
		<div>
			<%= link_to("reply", comment, :class => "reply-link") %>
		</div>
	</div>
</li>	

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id),
 							:remote => true do |f| %>
	<div><%= f.hidden_field :followed_id %></div>
	<div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
	<% if current_user.following?(@user) %>
		<%= render 'unfollow' %>
	<% else %>
		<%= render 'follow' %>
	<% end %>
	</div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
</li>

app/views/users/comments.html.erb
<h1>Comments by <%= @user.name %></h1>

<ol class="list">
	<% @comments.each do |c| %>
		<%= render :partial => 'users/comment',
							 :locals => {:comment => c} %>
	<% end %>
</ol>

<%= will_paginate @comments %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<p>All fields are optional.</p>
<%= semantic_form_for @user do |f| %>
	<%= f.inputs do %>
		<%= f.input :email %>
		<%= f.input :password, :label => "New password" %>
		<%= f.input :password_confirmation, :label => "New password confirmation" %>
	
	<%= f.semantic_fields_for :profile do |p| %>
		<%= p.input :city %>
		<%= p.input :occupation, :hint => "Be descriptive, e.g. \"Marketing Strategy Consultant\" rather than \"Associate\", \"History Major\" rather than \"Student\" " %>
		<%= p.input :organization, :hint => "Where you work or study" %>
		<%= p.input :organization_url %>
		<%= p.input :linkedin_url, :label => "LinkedIn url", :hint => "public profile url, e.g. http://www.linkedin.com/pub/tim-koelkebeck/1/a11/a86" %>
		<%= p.input :twitter_url %>
		<%= p.input :facebook_url %>
		<%= p.input :blog_url %>
		<%= p.input :personal_url %>
		<%= p.input :email_public, :label => "Allow members to see my email" %>
		<%= p.input :about %>
	<% end %>
	<% end %>
	<% f.buttons do %>
		<%= f.commit_button :label => "Update" %>
	<% end %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/links.html.erb
<h1>Links Submitted by <%= @user.name %></h1>

<ol class="list">
	<% @links.each_index do |i| %>
		<%= render 	:partial => 'shared/link',
								:locals => {:link => @links[i], :rank => base_rank + i + 1} %>
	<% end %>
</ol>

<%= will_paginate @links %>

app/views/users/new_from_tutorial.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user %>
<%= link_to("Edit your account", edit_user_registration_path(@user)) %> |
<% end %>
<%= link_to("All users", users_path)%>
<br /><br />

<table class="profile">
	<tr>
		<td valign=top>Name:</td>
		<td><%= @user.name %></td>
	</tr>
	
	<% if @work %>
	<tr>
		<td valign=top>Work:</td>
		<td>
			<% if @user.profile.occupation.present? %>
				<%= @user.profile.occupation %>
				<% if @user.profile.organization.present? %>
				at
				<% end %>
			<% end %>
			<% if @user.profile.organization.present? %>
				<% if @user.profile.organization_url.present? %>
					<%= link_to @user.profile.organization, @user.profile.organization_url %>
				<% else %>
					<%= @user.profile.organization %>
				<% end %>
			<% end %>
		</td>
	</tr>
	<% end %>

	<% if @user.profile.city.present? %>
	<tr>
		<td valign=top>City:</td>
		<td><%= @user.profile.city %></td>
	</tr>
	<% end %>
	
	<tr>
		<td valign=top>Karma:</td>
		<td><%= @user.karma %></td>
	</tr>

	<tr>
		<td valign=top>Hive&nbsp;activity:</td>
		<td>
		<% if @activity %>
			<% previous = false%>
			<% if !@user.links.empty? %>
			<%= link_to("link submissions", links_user_path(@user)) %> 
			<% previous = true %>
			<% end %>
			<% if !@user.comments.empty? %>
			<% if previous %> | <% end %>
			<%= link_to("comments", 				comments_user_path(@user)) %> 
			<% end %>
			<% if !@link_votes.empty? %>
			<% if previous %> | <% end %>
			<%= link_to("upvoted links",		upvoted_user_path(@user)) %>
			<% end %>
		<% else %>
			none
		<% end %>
		</td>
	</tr>
	<% if @user.profile.about.present? %>
	<tr>
		<td valign=top>About:</td>
		<td><%= auto_link(simple_format(@user.profile.about)).html_safe %></td>
	</tr>
	<% end %>
	
	<% if @any_url %>
	<tr>
		<td valign=top>Find Me:</td>
		<td>
			<% previous = false%>
			<% if @user.profile.linkedin_url.present? %>
				<%= link_to "LinkedIn", @user.profile.linkedin_url %>
				<% previous = true%>
			<% end %>
			<% if @user.profile.twitter_url.present? %>
				<% if previous %> | <% end %>
				<%= link_to "Twitter", @user.profile.twitter_url %>
			<% end %>
			<% if @user.profile.blog_url.present? %>
				<% if previous %> | <% end %>
				<%= link_to "Blog", @user.profile.blog_url %>
			<% end %>
			<% if @user.profile.personal_url.present? %>
				<% if previous %> | <% end %>
				<%= link_to "Personal Site", @user.profile.personal_url %>
			<% end %>
			<% if @user.profile.facebook_url.present? %>
				<% if previous %> | <% end %>
				<%= link_to "Facebook", @user.profile.facebook_url %>
			<% end %>	
		</td>
	</tr>
	<% end %>
	
	<% if @user.profile.email_public %>
	<tr>
		<td valign=top>Email:</td>
		<td><%= @user.email %></td>
	</tr>
	<% end %>
</table>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
      
      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, :size => 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>