config/routes.rb
Libertyhive::Application.routes.draw do

  match '/users/sign_up', :to => 'links#index'  #temporarily blocking open sign up

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
    
  resources :users do
    member do
      get :comments, :links, :upvoted
    end
  end
    
  resources :links
  resources :comments
  resources :votes
  
  root :to => 'links#index'
  

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="bar"></div>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
			<% if false %>
			<iframe src="http://www.facebook.com/plugins/like.php?href=www.hivechatter.com"
			        scrolling="no" frameborder="0"
			        style="border:none; width:450px; height:80px"><iframe>
			<% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="site-title">
		<%= link_to "Liberty Hive", root_path, :class => "site-title" %>
		<span class="beta">beta</span>
	</div>
	<nav>
    <ul>
	    <% if user_signed_in? %>
			<li><%= link_to "Submit", new_link_path %></li>
			<li><%= link_to "Invite", new_user_invitation_path %></li>
			<li><%= link_to current_user.name, current_user %></li>
		  <li><%= link_to "Sign out", destroy_user_session_path %></li>
		  <% else %>
			<% if false %> <li><%= link_to "Sign up", new_user_registration_path %></li> <% end %>
			<li><%= link_to "Sign in", new_user_session_path %></li>
		  <% end %>
    </ul>
  </nav>
	<div class="bar"></div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'reset', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'formtastic', 'formtastic_changes' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag :defaults %>
		<%= javascript_include_tag 'jquery' %>
		<%= javascript_include_tag 'hive' %>

	</head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section>
        <% flash.each do |key, value| %>
					<div class="flash"><%= value %></div>
				<% end %>
				<%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Libertarian Hive</title>
	<%= csrf_meta_tag %>
	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  <%= stylesheet_link_tag 'reset', 'landing_page/custom',
 													'formtastic', 'formtastic_changes' %>
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= javascript_include_tag :defaults %>
</head>

<body>
	
	<%= image_tag("background.jpg", :alt => "Statue of Liberty", 
																	:id => "background") %>
	
	<div id="container">
		<h1 id="site_title">Libertarian Hive</h1>
		<div id="blue_box">	<%= yield %>	</div>	
		<div id="links">
			<%= link_to "about", about_path %> &nbsp; | &nbsp;
			<%= link_to "contact", contact_path %> &nbsp; | &nbsp;
			<%= link_to "sign up", root_path %>
		</div>
	</div>
	<p id="copyright"> &copy; <%= DateTime.now.year %></p>
</body>
</html>